# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "cyberxml/pfsense-ce-232-64"

  # External Router
  config.vm.define "rtr_ext" do |rtr_ext|
    rtr_ext.vm.box = "cyberxml/pfsense-ce-232-64"
    rtr_ext.vm.hostname = "rtr-ext"
    rtr_ext.ssh.shell = 'sh'
    rtr_ext.ssh.username = 'vagrant'
    rtr_ext.ssh.password = 'vagrant'
    rtr_ext.vm.network "private_network", ip: "10.10.1.1", virtualbox__intnet: true
    rtr_ext.vm.network "private_network", ip: "10.10.2.1", virtualbox__intnet: true
    rtr_ext.vm.network "forwarded_port", guest: 443, host: 55433
    rtr_ext.vm.synced_folder ".", "/vagrant", disabled: true
  end

  # DMZ Router
  config.vm.define "rtr_dmz" do |rtr_dmz|
    rtr_dmz.vm.box = "cyberxml/pfsense-ce-232-64"
    rtr_dmz.vm.hostname = "rtr-dmz"
    rtr_dmz.ssh.shell = 'sh'
    rtr_dmz.ssh.username = 'vagrant'
    rtr_dmz.ssh.password = 'vagrant'
    rtr_dmz.vm.network "private_network", ip: "10.10.2.2", virtualbox__intnet: true
    rtr_dmz.vm.network "private_network", ip: "10.10.5.2", virtualbox__intnet: true
    rtr_dmz.vm.network "private_network", ip: "10.10.3.2", virtualbox__intnet: true
    rtr_dmz.vm.network "private_network", ip: "10.10.4.2", virtualbox__intnet: true
    rtr_dmz.vm.network "forwarded_port", guest: 443, host: 55434
    rtr_dmz.vm.synced_folder ".", "/vagrant", disabled: true
    rtr_dmz.vm.provision "file", source: "conf/config.rtr_dmz", destination: "/cf/conf/config.xml"
  end

  # INT Router
  config.vm.define "rtr_int" do |rtr_int|
    rtr_int.vm.box = "cyberxml/pfsense-ce-232-64"
    rtr_int.vm.hostname = "rtr-int"
    rtr_int.ssh.shell = 'sh'
    rtr_int.ssh.username = 'vagrant'
    rtr_int.ssh.password = 'vagrant'
    rtr_int.vm.network "private_network", ip: "10.10.5.1", virtualbox__intnet: true
    rtr_int.vm.network "private_network", ip: "10.10.6.1", virtualbox__intnet: true
    rtr_int.vm.network "private_network", ip: "10.10.7.1", virtualbox__intnet: true
    rtr_int.vm.network "forwarded_port", guest: 443, host: 55435
    rtr_int.vm.synced_folder ".", "/vagrant", disabled: true
    rtr_int.vm.provision "file", source: "conf/config.rtr_int", destination: "/cf/conf/config.xml"
  end

  # Enterprise Router
  config.vm.define "rtr_ent" do |rtr_ent|
    rtr_ent.vm.box = "cyberxml/pfsense-ce-232-64"
    rtr_ent.vm.hostname = "rtr-ent"
    rtr_ent.ssh.shell = 'sh'
    rtr_ent.ssh.username = 'vagrant'
    rtr_ent.ssh.password = 'vagrant'
    rtr_ent.vm.network "private_network", ip: "10.10.6.2", virtualbox__intnet: true
    rtr_ent.vm.network "private_network", ip: "10.10.8.1", virtualbox__intnet: true
    rtr_ent.vm.network "private_network", ip: "10.10.9.1", virtualbox__intnet: true
    rtr_ent.vm.network "forwarded_port", guest: 443, host: 55436
    rtr_ent.vm.synced_folder ".", "/vagrant", disabled: true
    rtr_ent.vm.provision "file", source: "conf/config.rtr_ent", destination: "/cf/conf/config.xml"
  end

  # Development Router
  config.vm.define "rtr_dev" do |rtr_dev|
    rtr_dev.vm.box = "cyberxml/pfsense-ce-232-64"
    rtr_dev.vm.hostname = "rtr-dev"
    rtr_dev.ssh.shell = 'sh'
    rtr_dev.ssh.username = 'vagrant'
    rtr_dev.ssh.password = 'vagrant'
    rtr_dev.vm.network "private_network", ip: "10.10.7.2", virtualbox__intnet: true
    rtr_dev.vm.network "private_network", ip: "10.10.10.1", virtualbox__intnet: true
    rtr_dev.vm.network "private_network", ip: "10.10.11.1", virtualbox__intnet: true
    rtr_dev.vm.network "forwarded_port", guest: 443, host: 55437
    rtr_dev.vm.synced_folder ".", "/vagrant", disabled: true
    rtr_dev.vm.provision "file", source: "conf/config.rtr_dev", destination: "/cf/conf/config.xml"
  end

end
