# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # Samba4 Active Directory
  config.vm.define "dc1" do |dc1|
    dc1.vm.box = "centos/7"
    dc1.vm.hostname = "dc1"
    dc1.vm.network "private_network", ip: "10.10.8.11", gateway: "10.10.8.1", virtualbox__intnet: true
    dc1.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  end

  # Postfix/Dovecot
  config.vm.define "mail" do |mail|
    mail.vm.box = "centos/7"
    mail.vm.hostname = "mail"
    mail.vm.network "private_network", ip: "10.10.8.13", gateway: "10.10.8.1", virtualbox__intnet: true
    mail.vm.network "forwarded_port", guest: 80, host:12380
    mail.vm.network "forwarded_port", guest: 443, host:12381
    mail.vm.network "forwarded_port", guest: 389, host:13389
    mail.vm.network "forwarded_port", guest: 636, host:13636
    mail.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  end

  # Web/Database Wordpress
  config.vm.define "web" do |web|
    web.vm.box = "centos/7"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "10.10.8.14", gateway: "10.10.8.1", virtualbox__intnet: true
    web.vm.network "forwarded_port", guest: 80, host:14080
    web.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  end

  # File Server: NFS
  config.vm.define "file" do |file|
    file.vm.box = "centos/7"
    file.vm.hostname = "files"
    file.vm.network "private_network", ip: "10.10.8.15", gateway: "10.10.8.1", virtualbox__intnet: true
    file.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  end

  # File Server: SMB
  config.vm.define "smb" do |smb|
    smb.vm.box = "centos/7"
    smb.vm.hostname = "smb"
    smb.vm.network "private_network", ip: "10.10.8.16", gateway: "10.10.8.1", virtualbox__intnet: true
    smb.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  end

end
