# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # Nagios Server
  # vi /etc/nagios.cfg
  # enable switch.cfg
  config.vm.define "nagios" do |nagios|
    nagios.vm.box = "ubuntu/xenial64"
    nagios.vm.hostname = "nagios.example.net"
    #nagios.ssh.shell = 'sh'
    #nagios.ssh.username = 'vagrant'
    #nagios.ssh.password = 'vagrant'
    nagios.vm.network "private_network", ip: "10.10.4.3", virtualbox__intnet: true
    nagios.vm.network "forwarded_port", guest: 80, host:5080 

    nagios.vm.provision "docker" do |d|
      d.run "nlmacamp/check_mk",
        image: "nlmacamp/check_mk",
        args: "-d -p '80:5000'"
    end
  end

  # ElasticSearch / ELK
  # need to resize for min of 3GB RAM
  config.vm.define "elastic" do |elastic|
    elastic.vm.box = "centos/7"
    elastic.vm.hostname = "elastic.example.net"
    elastic.vm.network "private_network", ip: "10.10.4.4", virtualbox__intnet: true
    elastic.vm.network "forwarded_port", guest: 9200, host:9200
    elastic.vm.network "forwarded_port", guest: 5601, host:5601
    elastic.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  end

=begin
  # Graylog
  config.vm.define "graylog" do |graylog|
    graylog.vm.box = "ubuntu/trusty64"
    graylog.vm.hostname = "graylog"

    graylog.vm.network :forwarded_port, guest: 80, host: 8080
    graylog.vm.network :forwarded_port, guest: 12201, host: 12201, protocol: 'udp'
    graylog.vm.network :forwarded_port, guest: 12201, host: 12201, protocol: 'tcp'

    graylog.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end

    $script = <<SCRIPT
      apt-get update
      echo 'Going to download Graylog...'
      curl -S -s -L -O https://packages.graylog2.org/releases/graylog-omnibus/ubuntu/graylog_latest.deb
      dpkg -i graylog_latest.deb
      rm graylog_latest.deb
      graylog-ctl set-external-ip http://127.0.0.1:8080/api
      graylog-ctl reconfigure
SCRIPT

    graylog.vm.provision "shell", inline: $script
  end
=end

  # SOC Workstation
  config.vm.define "socws101" do |socws101|
    socws101.vm.box = "boxcutter/centos72-desktop"
    socws101.vm.hostname = "socws101"
    socws101.vm.network "private_network", ip: "10.10.4.101", nameserver1: "10.10.8.11", gateway: "10.10.4.2", virtualbox__intnet: true
    # yum -y install firefox
  end
  # SOC Workstation
  config.vm.define "socws102" do |socws102|
    socws102.vm.box = "boxcutter/centos72-desktop"
    socws102.vm.hostname = "socws102"
    socws102.vm.network "private_network", ip: "10.10.4.102", nameserver1: "10.10.8.11", gateway: "10.10.4.2", virtualbox__intnet: true
    # yum -y install firefox
  end
end
