# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # https://www.howtoforge.com/tutorial/perfect-server-debian-8-jessie-apache-bind-dovecot-ispconfig-3/
  config.vm.define "dmzmail" do |dmzmail|
    dmzmail.vm.box = "centos/7"
    dmzmail.vm.hostname = "dmzmail"
    dmzmail.vm.network "private_network", ip: "10.10.3.4", gateway: "10.10.3.2", virtualbox__intnet: true
    dmzmail.vm.network "forwarded_port", guest: 12321, host:32321
    dmzmail.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  end
end
