# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # http://jensd.be/197/linux/basic-master-and-slave-dns-setup-with-bind
  # http://jensd.be/160/linux/split-horizon-dns-masterslave-with-bind
  config.vm.define "dmzdns" do |dmzdns|
    dmzdns.vm.box = "centos/7"
    dmzdns.vm.hostname = "dmzdns"
    dmzdns.vm.network "forwarded_port", guest: 22, host:22301
    dmzdns.vm.network "private_network", ip: "10.10.3.3", virtualbox__intnet: true
    dmzdns.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  end

  # https://www.howtoforge.com/tutorial/perfect-server-debian-8-jessie-apache-bind-dovecot-ispconfig-3/
  # http://www.linuxmail.info/postfix-smtp-gateway/
  # http://xmodulo.com/mailscanner-clam-antivirus-spamassassin-centos.html
  config.vm.define "dmzmail" do |dmzmail|
    dmzmail.vm.box = "centos/7"
    dmzmail.vm.hostname = "dmzmail"
    dmzmail.vm.network "private_network", ip: "10.10.3.4", gateway: "10.10.3.2", virtualbox__intnet: true
    dmzmail.vm.network "forwarded_port", guest: 22, host:22302
    dmzmail.vm.network "forwarded_port", guest: 12321, host:32321
    dmzmail.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  end

  config.vm.define "dmzweb" do |dmzweb|
    dmzweb.vm.box = "centos/7"
    dmzweb.vm.hostname = "dmzweb"
    dmzweb.vm.network "forwarded_port", guest: 22, host:22303
    dmzweb.vm.network "private_network", ip: "10.10.3.5", virtualbox__intnet: true
    dmzweb.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  end

  config.vm.define "proxy" do |proxy|
    proxy.vm.box = "centos/7"
    proxy.vm.hostname = "proxy"
    proxy.vm.network "forwarded_port", guest: 22, host:22304
    proxy.vm.network "private_network", ip: "10.10.3.6", virtualbox__intnet: true
    proxy.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  end
end
