# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "entwks101" do |entwks101|
    entwks101.vm.box = "artem-sidorenko/mint-18.0-cinnamon"
    entwks101.vm.hostname = "entwks101"
    entwks101.vm.network "private_network", ip: "10.10.9.101", virtualbox__intnet: true
  end
end
